name: Build ASI Plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Remove old plugin-sdk if exists
      shell: pwsh
      run: |
        if (Test-Path "plugin-sdk") {
          Remove-Item -Recurse -Force "plugin-sdk"
        }

    - name: Clone plugin-sdk
      run: |
        git clone --depth 1 https://github.com/DK22Pac/plugin-sdk.git plugin-sdk

    - name: Configure CMake
      run: cmake -B build -S . -G "Visual Studio 16 2019" -A Win32

    - name: Build Project
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AmazingTreasureESP-ASI
        path: build/Release/*.asi
